### ISSUE TITLE
Any chance VertUI could be tested for FreeCAD 1.0 release ?

### ISSUE THREAD

**Issue by luzpaz** [StudioPetrikas/FreeCADLink_VertUI#12]
https://blog.freecad.org/2024/09/24/the-second-release-candidate-of-freecad-1-0-is-out/

**Comment by StudioPetrikas** [comment]
I'll give it a try sometime. But I think FreeCAD has a lot of new functionality for themes that I have not investigated and I'm unfamiliar with.

**Comment by luzpaz** [comment]
> I'll give it a try sometime. But I think FreeCAD has a lot of new functionality for themes that I have not investigated and I'm unfamiliar with.

@StudioPetrikas perhaps you'd consider applying for an [FPA grant](https://fpa.freecad.org/handbook/process/grant-program-rules.html) to help fund this exploration? You have some great insights and approaches to UI/UX that would probably benefit FreeCAD UI/UX as a whole. I still think about your proposal for the start screen that you made back in the day...

**Comment by StudioPetrikas** [comment]
Very unlikely that I'd be chosen, since one of the committee members was rather hostile to me on the forums.
Thanks for the kind words though!

**Comment by luzpaz** [comment]
Sorry to hear that. That is a shame. Would you be OK if i communicated this to Yorik and see what he says ? I mean, if the proposal is solid (idea, code, execution) then it by principle it could be accepted by its merit.

**Comment by StudioPetrikas** [comment]
No, please don't. FreeCAD now has a great framework, vision, leadership, roadmap... Something that it didn't have when I started using it and "improving" it. Most of my ideas and designs have already aged, and I do not want to be a stick between the spokes.
