### ISSUE TITLE
VertUI with TechDraw document loaded clashes with 'Python console' and 'Report view' transparency

### ISSUE THREAD

**Issue by luzpaz** [StudioPetrikas/FreeCADLink_VertUI#3]
![image](https://user-images.githubusercontent.com/4140247/149208466-14d4319c-9346-49c0-aff4-7861d9a812c7.png)

Is this a ProDark .qss issue or VertUI .qss ?

**Comment by StudioPetrikas** [comment]
This is an overlay .qss issue. I wonder if it's possible to control the level of transparency depending on whether a drawing is open. 
I personally either turn off transparency manually (the little eye icon on the left), or make the two panels auto-hide, when I'm in tech-drawing mode.

**Comment by luzpaz** [comment]
@realthunder quick question, is there a way to make the overlay aware of the the color behind it and have it dynamically adjust itself to compensate?

**Comment by StudioPetrikas** [comment]
@luzpaz is it really an issue? Shift + F3 makes the overlay opaque. I think that's what the transparency switching was made for. 

I think programming a running 'service' that checks the background might be an overkill for such a minute improvement IMO.

**Comment by luzpaz** [comment]
Fair enough but it would still tickle me to know if this is possible. After digging some, it would be totally doable with QtQuick but we don't use that library

**Comment by StudioPetrikas** [comment]
A dirty way of doing it would be to switch the transparency whenever Tech Draw is activated. But that's not something I can do with QSS.

**Comment by realthunder** [comment]
> quick question, is there a way to make the overlay aware of the the color behind it and have it dynamically adjust itself to compensate?

@luzpaz It will be difficult to find a reliable way of doing it. Besides, it is hard to define a criteria for color switching. Like for example, in your posted screenshot, only half of the background is white. I think it will be more useful to make some overlay settings ( transparency, auto hide, etc) configurable based on the active view. Need to find a way to expose it to user. Maybe use a context menu for the button.
